#Playbook is list of tasks that can be executed against any server as part of the configuration management
#install any sw lik enginx using ansible or using playbook install nginx
- name: Install and run nginx module
  hosts: web
  #Root acceess we are using become cmd
  become: yes
  tasks:
  - name: Install nginx sw
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx service
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes    
