
- name: play level variables 
  host: local
  connection: local
  vars:
    COURSE: "DEVOPS"
    HOURS: "140HRS"
    TRAINER: "LAVANYA"

  tasks:
  - name: print variables
    vars:
    #local variable is defined inside the task and it is only available for that task. It is not available for other tasks in the playbook. Local variables are defined using the vars keyword inside the task.
      COURSE: "AWS"
    ansible.builtin.debug:
      #For varaibles we need to use double curly braces and the variable name inside it. This is 
      #called jinja2 syntax. We can use this syntax to print the value of the variable in the output.
      msg: "Hello course is: {{ COURSE }}, hello trainer is : {{ TRAINER }}, hello no of hrs: {{ HOURS }}"

      #in course var always print devops since local var is overwriting the global var but in trainer and hours it will print the global var since there is no local var defined for it. Local var has higher precedence than global var. If there is a local var defined for a variable then it will overwrite the global var for that variable. If there is no local var defined for a variable then it will use the global var for that variable.
