#this file is to understand username and password variables in ansible. We can use these variables to store the username and password of the server and then we can use these variables in the playbook to connect to the server. This way we can avoid hardcoding the username and password in the playbook and we can also easily manage the username and password in one place. We can also use these variables in multiple playbooks if needed. This way we can avoid duplication of username and password in multiple playbooks and we can also easily manage the username and password in one place.
- name: username and password variables
  hosts: local
  connection: local

  vars_promt:
  - name: username
    promt: "enter user name"
    #private no means username can see by all
    private: false

  - name: password
    promt: "enter password"
    #private yes means password can not be seen by anyone and it will be hidden when we enter the password. This is a security measure to protect the password from being exposed in the playbook or in the output.
    private: true

    tasks:
    - name: Print username and password
      ansible.builtin.debug:
        msg: "username is: {{username}} and password is: {{password}}"



 