;  orphan serevr
192.78.98.48 

[frontend]
192.78.98.46
192.78.98.47 
192.78.98.49

[backend]
192.78.98.45
192.78.98.46 
192.78.98.47

[web]
54.211.49.5

; If you want to print both frontend and backed severs, you can use the following command:
[roboshop:children]
frontend
backend

[local]
localhost

[local:vars]
COURSE: Ansible from inventory file

NAME: "Var from inventory file"




